window.AUTO_FACTOR_DATA={
  ranks:["G","F","E","D","C","B","A"],
  target:{
    id:"jetblack",
    name:"[Jetblack Automaton] シンボリクリスエス",
    initial:{芝:"A",ダート:"G",短距離:"G",マイル:"E",中距離:"A",長距離:"A",逃げ:"G",先行:"B",差し:"A",追込:"D"},
    desired:{芝:"A",ダート:"G",短距離:"G",マイル:"A",中距離:"A",長距離:"A",逃げ:"G",先行:"B",差し:"A",追込:"A"}
  },

  characters:{
    "ラインクラフト":{mile:"A",middle:"B",long:"G",dirt:"G",chase:"G",tags:["マイル親","相性"]},
    "ステイゴールド":{mile:"C",middle:"A",long:"A",dirt:"G",chase:"A",tags:["追込親","相性"]},
    "ダイワスカーレット":{mile:"A",middle:"A",long:"B",dirt:"G",chase:"G",tags:["マ中長","相性"]},
    "ジェンティルドンナ":{mile:"B",middle:"A",long:"A",dirt:"G",chase:"C",tags:["マ中長","相性"]},
    "エイシンフラッシュ":{mile:"F",middle:"A",long:"A",dirt:"G",chase:"C",tags:["中長","相性"]},
    "サトノクラウン":{mile:"F",middle:"A",long:"A",dirt:"G",chase:"C",tags:["中長","相性"]},
    "ウオッカ":{mile:"A",middle:"A",long:"F",dirt:"G",chase:"F",tags:["マ中","相性"]},
    "エアグルーヴ":{mile:"B",middle:"A",long:"E",dirt:"G",chase:"G",tags:["マ中","相性"]},
    "メジロラモーヌ":{mile:"A",middle:"A",long:"F",dirt:"G",chase:"G",tags:["マ中","相性"]},
    "シーザリオ":{mile:"B",middle:"A",long:"B",dirt:"G",chase:"C",tags:["マ中長","相性"]},
    "ヴィルシーナ":{mile:"A",middle:"A",long:"E",dirt:"G",chase:"G",tags:["マ中","相性"]},
    "オグリキャップ":{mile:"A",middle:"A",long:"B",dirt:"B",chase:"D",tags:["マ中長","ダート"]},
    "エルコンドルパサー":{mile:"A",middle:"A",long:"B",dirt:"B",chase:"C",tags:["マ中長","ダート"]},
    "イナリワン":{mile:"B",middle:"A",long:"A",dirt:"A",chase:"A",tags:["マ中長","ダート","追込"]},
    "ヒシアマゾン":{mile:"A",middle:"A",long:"B",dirt:"E",chase:"A",tags:["マ中長","追込"]},
    "ミスターシービー":{mile:"B",middle:"A",long:"A",dirt:"G",chase:"A",tags:["マ中長","追込"]},
    "アグネスデジタル":{mile:"A",middle:"A",long:"G",dirt:"A",chase:"C",tags:["マ中","ダート"]},
    "グラスワンダー":{mile:"A",middle:"B",long:"A",dirt:"G",chase:"F",tags:["マ中長"]},
    "オルフェーヴル":{mile:"C",middle:"A",long:"A",dirt:"G",chase:"A",tags:["中長","追込","相性"]},
    "ゴールドシップ":{mile:"C",middle:"A",long:"A",dirt:"G",chase:"A",tags:["中長","追込","相性"]},
    "ドリームジャーニー":{mile:"D",middle:"A",long:"A",dirt:"G",chase:"A",tags:["中長","追込","相性"]},
    "ナリタタイシン":{mile:"D",middle:"A",long:"A",dirt:"G",chase:"A",tags:["中長","追込"]},
    "メジロマックイーン":{mile:"F",middle:"A",long:"A",dirt:"G",chase:"F",tags:["中長","相性"]},
    "ナカヤマフェスタ":{mile:"F",middle:"A",long:"A",dirt:"G",chase:"C",tags:["中長","相性"]},
    "シンボリルドルフ":{mile:"C",middle:"A",long:"A",dirt:"G",chase:"C",tags:["マ中長"]},
    "マンハッタンカフェ":{mile:"F",middle:"B",long:"A",dirt:"G",chase:"C",tags:["中長"]},
    "アドマイヤベガ":{mile:"C",middle:"A",long:"B",dirt:"G",chase:"A",tags:["マ中長","追込"]}
  },

  slots:{
    mile:{
      base:"E",
      target:"マイル",
      nodes:{
        parent:{role:"親",prefs:["ラインクラフト","ウオッカ","オグリキャップ","エルコンドルパサー"]},
        gp1:{role:"祖父母①",prefs:["ダイワスカーレット","ウオッカ","エアグルーヴ","オグリキャップ"]},
        gp2:{role:"祖父母②",prefs:["ジェンティルドンナ","エアグルーヴ","メジロラモーヌ","シーザリオ"]},
        a1:{role:"曾祖父母①",prefs:["ウオッカ","オグリキャップ","エルコンドルパサー","イナリワン","アグネスデジタル"]},
        a2:{role:"曾祖父母②",prefs:["エアグルーヴ","オグリキャップ","エルコンドルパサー","ヒシアマゾン","グラスワンダー"]},
        a3:{role:"曾祖父母③",prefs:["シーザリオ","メジロラモーヌ","オグリキャップ","エルコンドルパサー","イナリワン"]},
        a4:{role:"曾祖父母④",prefs:["ヴィルシーナ","エアグルーヴ","ヒシアマゾン","ミスターシービー","オグリキャップ"]}
      }
    },
    chase:{
      base:"D",
      target:"追込",
      nodes:{
        parent:{role:"親",prefs:["ステイゴールド","オルフェーヴル","ゴールドシップ","ミスターシービー"]},
        gp1:{role:"祖父母①",prefs:["エイシンフラッシュ","オルフェーヴル","ゴールドシップ","シンボリルドルフ"]},
        gp2:{role:"祖父母②",prefs:["サトノクラウン","ゴールドシップ","オルフェーヴル","ナカヤマフェスタ"]},
        a1:{role:"曾祖父母①",prefs:["オルフェーヴル","ゴールドシップ","ドリームジャーニー","イナリワン","ヒシアマゾン"]},
        a2:{role:"曾祖父母②",prefs:["シンボリルドルフ","ミスターシービー","ヒシアマゾン","イナリワン","ナリタタイシン"]},
        a3:{role:"曾祖父母③",prefs:["ゴールドシップ","オルフェーヴル","ドリームジャーニー","イナリワン","ヒシアマゾン"]},
        a4:{role:"曾祖父母④",prefs:["ナカヤマフェスタ","メジロマックイーン","ミスターシービー","アドマイヤベガ","イナリワン"]}
      }
    }
  }
};
